# Generated by Django 5.1.3 on 2025-02-04 09:36

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0038_checklist_checklisttemplate_checklisttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
