name: Python package

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Explicitly include Python 3.9 only with Django 4
          - python-version: "3.9"
            django-version: "4"
            # Define the general matrix for Python with Django 
        python-version: ["3.10", "3.11", "3.12"]
        django-version: ["4"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-testing.txt')}}-${{ hashFiles('tox.ini') }}-${{ matrix.python-version }}-${{ matrix.django-version }} 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-testing.txt -c constraints-Django${{ matrix.django-version }}.txt

    - name: Lint with ruff
      run: |
        pip install ruff
        make checkformat


    - name: Test with pytest
      run: |
        pip install pytest
        cd ${GITHUB_WORKSPACE} && python quicktest.py
      env:
        DJANGO_SETTINGS_MODULE: helpdesk.settings

